version: "3"

tasks:
  npm-update:
    dir: swa/
    cmds:
      - container run --rm -it -v $(pwd):/app -w /app node:24 npm update

  astro-upgrade:
    dir: swa/
    cmds:
      - container run --rm -it -v $(pwd):/app -w /app node:24 npx @astrojs/upgrade

  # Setup node_modules and install dependencies
  # This command should be run after starting a new devcontainer or codespaces instance
  init-devcontainer:
    cmds:
      - |
        cd {{.TASKFILE_DIR}}/swa && \
        sudo chown codespace:codespace node_modules && \
        npm install

  build:
    dir: swa/
    cmds:
      - npm ci --no-audit --no-fund
      - npm run build
    sources:
      - swa/**
    generates:
      - swa/dist/**
      - swa/node_modules/**

  dev:
    dir: swa/
    cmds:
      - npm run dev

  docker-build:
    vars:
      SHORT_SHA:
        sh: git rev-parse --short HEAD
      REGISTRY: rg.fr-par.scw.cloud/clw-web-prod/clw-web-prod
    cmds:
      - >
        docker buildx build
        --platform linux/amd64
        --build-arg PUBLIC_RYBBIT_SITE_ID={{.PUBLIC_RYBBIT_SITE_ID}}
        -t {{.REGISTRY}}:{{.SHORT_SHA}}
        -t {{.REGISTRY}}:latest
        --push
        {{.CLI_ARGS}} .

  deploy:
    vars:
      SHORT_SHA:
        sh: git rev-parse --short HEAD
      REGISTRY: rg.fr-par.scw.cloud/clw-web-prod/clw-web-prod
    cmds:
      - task: docker-build
      - op run --env-file ./.env.1password -- env REGISTRY_IMAGE={{.REGISTRY}}:{{.SHORT_SHA}} ./node_modules/.bin/serverless deploy
