version: "3"

tasks:
  npm-update:
    dir: swa/
    cmds:
      - container run --rm -it -v $(pwd):/app -w /app node:24 npm update

  astor-upgrade:
    dir: api/
    cmds:
      - container run --rm -it -v $(pwd):/app -w /app node:24 npx @astrojs/upgrade

  npm-install:
    cmds:
      - |
        cd {{.TASKFILE_DIR}}/api && \
        sudo chown codespace:codespace node_modules && \
        npm install
      - |
        cd {{.TASKFILE_DIR}}/swa && \
        sudo chown codespace:codespace node_modules && \
        npm install

  build:
    cmds:
      - |
        swa build \
          --api-location api/ \
          --api-build-command 'cd {{.TASKFILE_DIR}}/api && npm run build' \
          --app-location swa/ \
          --app-build-command 'cd {{.TASKFILE_DIR}}/swa && npm run build'
    sources:
      - api/**
      - swa/**
    generates:
      - api/dist/**
      - api/node_modules/**
      - swa/dist/**
      - swa/node_modules/**

  build-devserver:
    cmds:
      - |
        swa build \
          --api-location api/ \
          --api-build-command 'cd {{.TASKFILE_DIR}}/api && npm run watch' \
          --app-location swa/ \
          --app-build-command 'cd {{.TASKFILE_DIR}}/swa && npm run build'

  run:
    deps:
      - build
    cmds:
      - |
        PATH="/opt/homebrew/opt/node@18/bin:$PATH"
        source .env
        swa start \
          --app-location {{.TASKFILE_DIR}}/swa/ \
          --app-devserver-url http://localhost:4321 \
          --api-location {{.TASKFILE_DIR}}/api/ \
          --run 'npm run dev'
